version: '3'
services:
   # Eth node for testing purposes
  eth:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

  exchange-service:
    build: ./exchange-service
    ports:
      - "3001:3001"
    depends_on:
      - eth
    command: ["yarn", "start", "--eth-node-url", "http://eth"]
    environment:
        MAIL_PASS: <AL to fix for prod>
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
