export const RESET = "RESET";

// -- authenticate --
export const AUTHENTICATED = "AUTHENTICATED";
export const AUTHENTICATING = "AUTHENTICATING";
export const AUTHENTICATING_COMPLETED = "AUTHENTICATING_COMPLETED";
export const AUTHENTICATING_FAILED = "AUTHENTICATING_FAILED";
export const AUTHENTICATION_RESET = "AUTHENTICATION_RESET";

// --- search ---
export const SEARCH_FETCHING = "SEARCH_FETCHING";
export const SEARCH_FETCHING_COMPLETED = "SEARCH_FETCHING_COMPLETED";
export const SEARCH_FETCHING_FAILED = "SEARCH_FETCHING_FAILED";
export const SEARCH_LOAD = "SEARCH_LOAD";
export const SEARCH_LOAD_MORE = "SEARCH_LOAD_MORE";

// -- user registration --
export const USER_REGISTRATION_REQUEST_SENT = "USER_REGISTRATION_REQUEST_SENT";
export const USER_REGISTRATION_REQUEST_COMPLETED =
    "USER_REGISTRATION_REQUEST_COMPLETED";
export const USER_REGISTRATION_REQUEST_FAILED =
    "USER_REGISTRATION_REQUEST_FAILED";
export const USER_REGISTERED = "USER_REGISTERED";
