export const RESET = "RESET";

// -- authenticate --
export const AUTHENTICATED = "AUTHENTICATED";
export const AUTHENTICATING = "AUTHENTICATING";
export const AUTHENTICATING_COMPLETED = "AUTHENTICATING_COMPLETED";
export const AUTHENTICATING_FAILED = "AUTHENTICATING_FAILED";
export const AUTHENTICATION_RESET = "AUTHENTICATION_RESET";

// -- loan lifecycle --
export const LOAN_CREATED = "LOAN_CREATED";
export const LOAN_APPROVED_BY_LENDER = "LOAN_APPROVED_BY_LENDER";
export const LOAN_TERMS_ACCEPTED = "LOAN_TERMS_ACCEPTED";
export const LOAN_MONEY_SENT = "LOAN_MONEY_SENT";
export const LOAN_MONEY_RECEIVED = "LOAN_MONEY_RECEIVED";
export const LOAN_PAYMENT_SENT = "LOAN_PAYMENT_SENT";
export const LOAN_PAYMENT_RECEIVED = "LOAN_PAYMENT_RECEIVED";
export const LOAN_CLOSED = "LOAN_CLOSED";
export const LOAN_POSTED = "LOAN_POSTED";
export const LOAN_POSTED_COMPLETED = "LOAN_POSTED_COMPLETED";
export const LOAN_POSTED_FAILED = "LOAN_POSTED_FAILED";

// -- loan --
export const LOAN = "LOAN";
export const LOAN_FETCHING = "LOAN_FETCHING";
export const LOAN_FETCHING_COMPLETED = "LOAN_FETCHING_COMPLETED";
export const LOAN_FETCHING_FAILED = "LOAN_FETCHING_FAILED";

// -- loans --
export const LOANS = "LOANS";
export const LOANS_FETCHING = "LOANS_FETCHING";
export const LOANS_FETCHING_COMPLETED = "LOANS_FETCHING_COMPLETED";
export const LOANS_FETCHING_FAILED = "LOANS_FETCHING_FAILED";
